import Providers from './Providers'
import Navbar from './Navbar'
import '@/styles/globals.css'

export default function AppLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='it'>
			<head>
				<title>Sentire a colori</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</head>
			<body>
				<Providers>
					<Navbar />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
